[package]
name = "docs-pack-forms"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
leptos = { version = "0.8.15", default-features = false, features = ["csr"] }
ui = { path = "../../crates/ui", default-features = false, features = ["inject-css", "component-checkbox", "component-input"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.85", features = ["Location", "Window"] }
