[package]
name = "web-demo"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
leptos = { version = "0.8.15", default-features = false, features = ["csr"] }
ui = { path = "../../crates/ui", default-features = false, features = ["inject-css", "web-demo-components"] }
ui-layout = { path = "../../crates/ui-layout", default-features = false, features = ["inject-css", "web-demo-components"] }
ui-state-primitives = { path = "../../crates/ui-state-primitives" }
ui-headless = { path = "../../crates/ui-headless" }

[dev-dependencies]
any_spawner = { version = "0.3", features = ["futures-executor"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = ["cfg(erase_components)"]
