[package]
name = "ui-text-input"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[features]
default = []

[dependencies]
ui-observability = { path = "../../crates/ui-observability" }
ui = { path = "../../crates/ui", default-features = false, features = ["component-domain-text_input"] }
