use super::{CheckboxLayoutTokens, CommandLayoutTokens};

pub const CHECKBOX_LAYOUT_TOKENS_MEDIUM: CheckboxLayoutTokens = CheckboxLayoutTokens {
    gap_px: 10,
    disabled_opacity_percent: 50,
    focus_outline_width_px: 3,
    focus_outline_offset_px: 2,
    box_size_default_px: 20,
    box_size_sm_px: 18,
    box_size_lg_px: 24,
    box_radius_default_px: 4,
    box_radius_sm_px: 5,
    box_radius_lg_px: 7,
    indicator_size_default_px: 14,
    indicator_size_sm_px: 12,
    indicator_size_lg_px: 16,
};

pub const CHECKBOX_LAYOUT_TOKENS_LARGE: CheckboxLayoutTokens = CheckboxLayoutTokens {
    gap_px: 10,
    disabled_opacity_percent: 50,
    focus_outline_width_px: 3,
    focus_outline_offset_px: 2,
    box_size_default_px: 20,
    box_size_sm_px: 18,
    box_size_lg_px: 24,
    box_radius_default_px: 4,
    box_radius_sm_px: 5,
    box_radius_lg_px: 7,
    indicator_size_default_px: 14,
    indicator_size_sm_px: 12,
    indicator_size_lg_px: 16,
};

pub const COMMAND_LAYOUT_TOKENS_MEDIUM: CommandLayoutTokens = CommandLayoutTokens {
    panel_max_width_px: 480,
    list_max_height_px: 336,
    disabled_opacity_percent: 64,
    input_wrap_padding_px: 8,
    input_wrap_border_mix_percent: 86,
    input_wrap_bg_mix_percent: 94,
    input_padding_block_px: 9,
    input_padding_inline_px: 12,
    input_focus_outline_width_px: 3,
    input_focus_outline_offset_px: 1,
    options_padding_px: 6,
    group_gap_px: 4,
    group_spacing_px: 6,
    group_border_mix_percent: 84,
    group_heading_padding_inline_px: 10,
    group_heading_letter_spacing_centiem: 2,
    group_items_gap_px: 2,
    option_gap_px: 12,
    option_padding_block_px: 9,
    option_padding_inline_px: 10,
    option_focus_mix_percent: 96,
    option_disabled_opacity_percent: 52,
    shortcut_border_mix_percent: 84,
    shortcut_bg_mix_percent: 88,
    shortcut_padding_inline_px: 6,
    shortcut_padding_block_px: 2,
    empty_padding_block_px: 14,
    empty_padding_inline_px: 12,
};

pub const COMMAND_LAYOUT_TOKENS_LARGE: CommandLayoutTokens = CommandLayoutTokens {
    panel_max_width_px: 480,
    list_max_height_px: 336,
    disabled_opacity_percent: 64,
    input_wrap_padding_px: 8,
    input_wrap_border_mix_percent: 86,
    input_wrap_bg_mix_percent: 94,
    input_padding_block_px: 9,
    input_padding_inline_px: 12,
    input_focus_outline_width_px: 3,
    input_focus_outline_offset_px: 1,
    options_padding_px: 6,
    group_gap_px: 4,
    group_spacing_px: 6,
    group_border_mix_percent: 84,
    group_heading_padding_inline_px: 10,
    group_heading_letter_spacing_centiem: 2,
    group_items_gap_px: 2,
    option_gap_px: 12,
    option_padding_block_px: 9,
    option_padding_inline_px: 10,
    option_focus_mix_percent: 96,
    option_disabled_opacity_percent: 52,
    shortcut_border_mix_percent: 84,
    shortcut_bg_mix_percent: 88,
    shortcut_padding_inline_px: 6,
    shortcut_padding_block_px: 2,
    empty_padding_block_px: 14,
    empty_padding_inline_px: 12,
};
