pub fn CheckboxGroup(
    id: String,
    label: String,
    description: Option<String>,
    error: Option<String>,
    is_invalid: leptos::prelude::Signal<bool>,
    is_required: leptos::prelude::Signal<bool>,
    is_disabled: bool,
    motion: crate::motion::CheckboxGroupMotion,
    lang: Option<String>,
    dir: Option<ui_headless::A11yDirection>,
    aria_describedby: leptos::prelude::Signal<Option<String>>,
    class_name: Option<String>,
    children: leptos::children::Children,
) -> impl leptos::prelude::IntoView;
