mod actions;
mod actions_extra;
mod collections;
mod collections_command;
mod collections_extra;
mod collections_groups;
mod display;
mod display_extra;
mod files;
mod forms;
mod forms_color;
mod forms_extra;
mod forms_groups;
mod forms_groups_extra;
mod layout;
mod layout_extra;
mod overlays;
mod overlays_extra;

use super::ComponentDoc;

pub(super) const CATALOG: &[ComponentDoc] = &[
    ComponentDoc {
        name: "Button",
        slug: "button",
        group: "Actions",
        page: actions::button,
    },
    ComponentDoc {
        name: "ActionBar",
        slug: "action-bar",
        group: "Actions",
        page: actions_extra::action_bar,
    },
    ComponentDoc {
        name: "ActionButton",
        slug: "action-button",
        group: "Actions",
        page: actions::action_button,
    },
    ComponentDoc {
        name: "FieldButton",
        slug: "field-button",
        group: "Actions",
        page: actions_extra::field_button,
    },
    ComponentDoc {
        name: "ClearButton",
        slug: "clear-button",
        group: "Actions",
        page: actions_extra::clear_button,
    },
    ComponentDoc {
        name: "CloseButton",
        slug: "close-button",
        group: "Actions",
        page: actions_extra::close_button,
    },
    ComponentDoc {
        name: "LogicButton",
        slug: "logic-button",
        group: "Actions",
        page: actions_extra::logic_button,
    },
    ComponentDoc {
        name: "ActionButtonGroup",
        slug: "action-button-group",
        group: "Actions",
        page: actions::action_button_group,
    },
    ComponentDoc {
        name: "ActionGroup",
        slug: "action-group",
        group: "Actions",
        page: actions_extra::action_group,
    },
    ComponentDoc {
        name: "ActionMenu",
        slug: "action-menu",
        group: "Actions",
        page: actions::action_menu,
    },
    ComponentDoc {
        name: "ButtonCopy",
        slug: "button-copy",
        group: "Actions",
        page: actions::button_copy,
    },
    ComponentDoc {
        name: "ButtonGroup",
        slug: "button-group",
        group: "Actions",
        page: actions::button_group,
    },
    ComponentDoc {
        name: "FlipButton",
        slug: "flip-button",
        group: "Actions",
        page: actions::flip_button,
    },
    ComponentDoc {
        name: "IconButton",
        slug: "icon-button",
        group: "Actions",
        page: actions::icon_button,
    },
    ComponentDoc {
        name: "LinkButton",
        slug: "link-button",
        group: "Actions",
        page: actions::link_button,
    },
    ComponentDoc {
        name: "SearchInputButton",
        slug: "search-input-button",
        group: "Actions",
        page: actions::search_input_button,
    },
    ComponentDoc {
        name: "ShareButton",
        slug: "share-button",
        group: "Actions",
        page: actions::share_button,
    },
    ComponentDoc {
        name: "ThemeToggleButton",
        slug: "theme-toggle-button",
        group: "Actions",
        page: actions::theme_toggle_button,
    },
    ComponentDoc {
        name: "ToggleButton",
        slug: "toggle-button",
        group: "Actions",
        page: actions::toggle_button,
    },
    ComponentDoc {
        name: "Toggle",
        slug: "toggle",
        group: "Actions",
        page: actions_extra::toggle,
    },
    ComponentDoc {
        name: "ToggleButtonGroup",
        slug: "toggle-button-group",
        group: "Actions",
        page: actions::toggle_button_group,
    },
    ComponentDoc {
        name: "Form",
        slug: "form",
        group: "Forms",
        page: forms::form,
    },
    ComponentDoc {
        name: "Input",
        slug: "input",
        group: "Forms",
        page: forms::input,
    },
    ComponentDoc {
        name: "Label",
        slug: "label",
        group: "Forms",
        page: forms_extra::label,
    },
    ComponentDoc {
        name: "Legend",
        slug: "legend",
        group: "Forms",
        page: forms_groups_extra::legend,
    },
    ComponentDoc {
        name: "Description",
        slug: "description",
        group: "Forms",
        page: forms_extra::description,
    },
    ComponentDoc {
        name: "FieldError",
        slug: "field-error",
        group: "Forms",
        page: forms_extra::field_error,
    },
    ComponentDoc {
        name: "ErrorMessage",
        slug: "error-message",
        group: "Forms",
        page: forms_extra::error_message,
    },
    ComponentDoc {
        name: "Field",
        slug: "field",
        group: "Forms",
        page: forms_extra::field,
    },
    ComponentDoc {
        name: "Fieldset",
        slug: "fieldset",
        group: "Forms",
        page: forms_extra::fieldset,
    },
    ComponentDoc {
        name: "FieldGroup",
        slug: "field-group",
        group: "Forms",
        page: forms_groups::field_group,
    },
    ComponentDoc {
        name: "HelpText",
        slug: "help-text",
        group: "Forms",
        page: forms_extra::help_text,
    },
    ComponentDoc {
        name: "InputGroup",
        slug: "input-group",
        group: "Forms",
        page: forms::input_group,
    },
    ComponentDoc {
        name: "DateInputGroup",
        slug: "date-input-group",
        group: "Forms",
        page: forms_groups::date_input_group,
    },
    ComponentDoc {
        name: "TextField",
        slug: "text-field",
        group: "Forms",
        page: forms::text_field,
    },
    ComponentDoc {
        name: "TextArea",
        slug: "text-area",
        group: "Forms",
        page: forms::text_area,
    },
    ComponentDoc {
        name: "Textarea",
        slug: "textarea",
        group: "Forms",
        page: forms_extra::textarea,
    },
    ComponentDoc {
        name: "SearchField",
        slug: "search-field",
        group: "Forms",
        page: forms::search_field,
    },
    ComponentDoc {
        name: "ColorField",
        slug: "color-field",
        group: "Forms",
        page: forms_color::color_field,
    },
    ComponentDoc {
        name: "ColorEditor",
        slug: "color-editor",
        group: "Forms",
        page: forms_color::color_editor,
    },
    ComponentDoc {
        name: "ColorArea",
        slug: "color-area",
        group: "Forms",
        page: forms_color::color_area,
    },
    ComponentDoc {
        name: "ColorSlider",
        slug: "color-slider",
        group: "Forms",
        page: forms_color::color_slider,
    },
    ComponentDoc {
        name: "ColorWheel",
        slug: "color-wheel",
        group: "Forms",
        page: forms_color::color_wheel,
    },
    ComponentDoc {
        name: "ColorThumb",
        slug: "color-thumb",
        group: "Forms",
        page: forms_color::color_thumb,
    },
    ComponentDoc {
        name: "ColorHandle",
        slug: "color-handle",
        group: "Forms",
        page: forms_color::color_handle,
    },
    ComponentDoc {
        name: "ColorLoupe",
        slug: "color-loupe",
        group: "Forms",
        page: forms_color::color_loupe,
    },
    ComponentDoc {
        name: "ColorPicker",
        slug: "color-picker",
        group: "Forms",
        page: forms_color::color_picker,
    },
    ComponentDoc {
        name: "NumberField",
        slug: "number-field",
        group: "Forms",
        page: forms::number_field,
    },
    ComponentDoc {
        name: "InputOtp",
        slug: "input-otp",
        group: "Forms",
        page: forms::input_otp,
    },
    ComponentDoc {
        name: "Checkbox",
        slug: "checkbox",
        group: "Forms",
        page: forms::checkbox,
    },
    ComponentDoc {
        name: "CheckboxField",
        slug: "checkbox-field",
        group: "Forms",
        page: forms_groups_extra::checkbox_field,
    },
    ComponentDoc {
        name: "FormField",
        slug: "form-field",
        group: "Forms",
        page: forms_groups_extra::form_field,
    },
    ComponentDoc {
        name: "CheckboxGroup",
        slug: "checkbox-group",
        group: "Forms",
        page: forms::checkbox_group,
    },
    ComponentDoc {
        name: "Switch",
        slug: "switch",
        group: "Forms",
        page: forms::switch,
    },
    ComponentDoc {
        name: "SwitchGroup",
        slug: "switch-group",
        group: "Forms",
        page: forms_groups::switch_group,
    },
    ComponentDoc {
        name: "RadioGroup",
        slug: "radio-group",
        group: "Forms",
        page: forms::radio_group,
    },
    ComponentDoc {
        name: "Radio",
        slug: "radio",
        group: "Forms",
        page: forms::radio,
    },
    ComponentDoc {
        name: "SegmentedControl",
        slug: "segmented-control",
        group: "Forms",
        page: forms::segmented_control,
    },
    ComponentDoc {
        name: "Slider",
        slug: "slider",
        group: "Forms",
        page: forms_extra::slider,
    },
    ComponentDoc {
        name: "Calendar",
        slug: "calendar",
        group: "Forms",
        page: forms_extra::calendar,
    },
    ComponentDoc {
        name: "DateField",
        slug: "date-field",
        group: "Forms",
        page: forms_extra::date_field,
    },
    ComponentDoc {
        name: "DatePicker",
        slug: "date-picker",
        group: "Forms",
        page: forms_extra::date_picker,
    },
    ComponentDoc {
        name: "DateRangePicker",
        slug: "date-range-picker",
        group: "Forms",
        page: forms_extra::date_range_picker,
    },
    ComponentDoc {
        name: "TimeField",
        slug: "time-field",
        group: "Forms",
        page: forms_extra::time_field,
    },
    ComponentDoc {
        name: "Card",
        slug: "card",
        group: "Layout",
        page: layout::card,
    },
    ComponentDoc {
        name: "View",
        slug: "view",
        group: "Layout",
        page: layout::view,
    },
    ComponentDoc {
        name: "Flex",
        slug: "flex",
        group: "Layout",
        page: layout::flex,
    },
    ComponentDoc {
        name: "Grid",
        slug: "grid",
        group: "Layout",
        page: layout_extra::grid,
    },
    ComponentDoc {
        name: "AspectRatio",
        slug: "aspect-ratio",
        group: "Layout",
        page: layout_extra::aspect_ratio,
    },
    ComponentDoc {
        name: "Content",
        slug: "content",
        group: "Layout",
        page: layout::content,
    },
    ComponentDoc {
        name: "Header",
        slug: "header",
        group: "Layout",
        page: layout::header,
    },
    ComponentDoc {
        name: "Footer",
        slug: "footer",
        group: "Layout",
        page: layout::footer,
    },
    ComponentDoc {
        name: "Heading",
        slug: "heading",
        group: "Layout",
        page: layout::heading,
    },
    ComponentDoc {
        name: "Divider",
        slug: "divider",
        group: "Layout",
        page: layout::divider,
    },
    ComponentDoc {
        name: "Separator",
        slug: "separator",
        group: "Layout",
        page: layout::separator,
    },
    ComponentDoc {
        name: "Spacer",
        slug: "spacer",
        group: "Layout",
        page: layout::spacer,
    },
    ComponentDoc {
        name: "Well",
        slug: "well",
        group: "Layout",
        page: layout::well,
    },
    ComponentDoc {
        name: "Surface",
        slug: "surface",
        group: "Layout",
        page: layout_extra::surface,
    },
    ComponentDoc {
        name: "ScrollShadow",
        slug: "scroll-shadow",
        group: "Layout",
        page: layout::scroll_shadow,
    },
    ComponentDoc {
        name: "AutoHeight",
        slug: "auto-height",
        group: "Layout",
        page: layout::auto_height,
    },
    ComponentDoc {
        name: "UiRoot",
        slug: "ui-root",
        group: "Layout",
        page: layout::ui_root,
    },
    ComponentDoc {
        name: "Alert",
        slug: "alert",
        group: "Display",
        page: display::alert,
    },
    ComponentDoc {
        name: "InlineAlert",
        slug: "inline-alert",
        group: "Display",
        page: display::inline_alert,
    },
    ComponentDoc {
        name: "Badge",
        slug: "badge",
        group: "Display",
        page: display::badge,
    },
    ComponentDoc {
        name: "StatusLight",
        slug: "status-light",
        group: "Display",
        page: display::status_light,
    },
    ComponentDoc {
        name: "Chip",
        slug: "chip",
        group: "Display",
        page: display::chip,
    },
    ComponentDoc {
        name: "Skeleton",
        slug: "skeleton",
        group: "Display",
        page: display::skeleton,
    },
    ComponentDoc {
        name: "SkeletonGroup",
        slug: "skeleton-group",
        group: "Display",
        page: display_extra::skeleton_group,
    },
    ComponentDoc {
        name: "CircularProgress",
        slug: "circular-progress",
        group: "Display",
        page: display::circular_progress,
    },
    ComponentDoc {
        name: "Spinner",
        slug: "spinner",
        group: "Display",
        page: display::spinner,
    },
    ComponentDoc {
        name: "Progress",
        slug: "progress",
        group: "Display",
        page: display::progress,
    },
    ComponentDoc {
        name: "ProgressBar",
        slug: "progress-bar",
        group: "Display",
        page: display::progress_bar,
    },
    ComponentDoc {
        name: "ProgressCircle",
        slug: "progress-circle",
        group: "Display",
        page: display::progress_circle,
    },
    ComponentDoc {
        name: "Meter",
        slug: "meter",
        group: "Display",
        page: display::meter,
    },
    ComponentDoc {
        name: "Code",
        slug: "code",
        group: "Display",
        page: display::code,
    },
    ComponentDoc {
        name: "CodeBlock",
        slug: "code-block",
        group: "Display",
        page: display::code_block,
    },
    ComponentDoc {
        name: "Kbd",
        slug: "kbd",
        group: "Display",
        page: display::kbd,
    },
    ComponentDoc {
        name: "Keyboard",
        slug: "keyboard",
        group: "Display",
        page: display_extra::keyboard,
    },
    ComponentDoc {
        name: "Snippet",
        slug: "snippet",
        group: "Display",
        page: display::snippet,
    },
    ComponentDoc {
        name: "Link",
        slug: "link",
        group: "Display",
        page: display::link,
    },
    ComponentDoc {
        name: "LabeledValue",
        slug: "labeled-value",
        group: "Display",
        page: display_extra::labeled_value,
    },
    ComponentDoc {
        name: "Text",
        slug: "text",
        group: "Display",
        page: display_extra::text,
    },
    ComponentDoc {
        name: "Avatar",
        slug: "avatar",
        group: "Display",
        page: display::avatar,
    },
    ComponentDoc {
        name: "AvatarGroup",
        slug: "avatar-group",
        group: "Display",
        page: display::avatar_group,
    },
    ComponentDoc {
        name: "Image",
        slug: "image",
        group: "Display",
        page: display::image,
    },
    ComponentDoc {
        name: "ColorSwatch",
        slug: "color-swatch",
        group: "Display",
        page: display_extra::color_swatch,
    },
    ComponentDoc {
        name: "ColorSwatchPicker",
        slug: "color-swatch-picker",
        group: "Display",
        page: display_extra::color_swatch_picker,
    },
    ComponentDoc {
        name: "Icon",
        slug: "icon",
        group: "Display",
        page: display_extra::icon,
    },
    ComponentDoc {
        name: "IllustratedMessage",
        slug: "illustrated-message",
        group: "Display",
        page: display::illustrated_message,
    },
    ComponentDoc {
        name: "EmptyState",
        slug: "empty-state",
        group: "Display",
        page: display_extra::empty_state,
    },
    ComponentDoc {
        name: "ErrorView",
        slug: "error-view",
        group: "Display",
        page: display_extra::error_view,
    },
    ComponentDoc {
        name: "PressableFeedback",
        slug: "pressable-feedback",
        group: "Display",
        page: display_extra::pressable_feedback,
    },
    ComponentDoc {
        name: "MotionRipple",
        slug: "motion-ripple",
        group: "Display",
        page: display::motion_ripple,
    },
    ComponentDoc {
        name: "StaticNumber",
        slug: "static-number",
        group: "Display",
        page: display::static_number,
    },
    ComponentDoc {
        name: "SlidingNumber",
        slug: "sliding-number",
        group: "Display",
        page: display::sliding_number,
    },
    ComponentDoc {
        name: "FileTrigger",
        slug: "file-trigger",
        group: "Files",
        page: files::file_trigger,
    },
    ComponentDoc {
        name: "DropZone",
        slug: "drop-zone",
        group: "Files",
        page: files::drop_zone,
    },
    ComponentDoc {
        name: "Breadcrumbs",
        slug: "breadcrumbs",
        group: "Collections",
        page: collections::breadcrumbs,
    },
    ComponentDoc {
        name: "Accordion",
        slug: "accordion",
        group: "Collections",
        page: collections::accordion,
    },
    ComponentDoc {
        name: "Disclosure",
        slug: "disclosure",
        group: "Collections",
        page: collections::disclosure,
    },
    ComponentDoc {
        name: "Collapsible",
        slug: "collapsible",
        group: "Collections",
        page: collections_groups::collapsible,
    },
    ComponentDoc {
        name: "DisclosureGroup",
        slug: "disclosure-group",
        group: "Collections",
        page: collections_extra::disclosure_group,
    },
    ComponentDoc {
        name: "Tabs",
        slug: "tabs",
        group: "Collections",
        page: collections::tabs,
    },
    ComponentDoc {
        name: "ListBox",
        slug: "listbox",
        group: "Collections",
        page: collections::list_box,
    },
    ComponentDoc {
        name: "ListBoxItem",
        slug: "listbox-item",
        group: "Collections",
        page: collections_extra::listbox_item,
    },
    ComponentDoc {
        name: "ListBoxSection",
        slug: "listbox-section",
        group: "Collections",
        page: collections_extra::listbox_section,
    },
    ComponentDoc {
        name: "Menu",
        slug: "menu",
        group: "Collections",
        page: collections::menu,
    },
    ComponentDoc {
        name: "MenuItem",
        slug: "menu-item",
        group: "Collections",
        page: collections_extra::menu_item,
    },
    ComponentDoc {
        name: "MenuSection",
        slug: "menu-section",
        group: "Collections",
        page: collections_extra::menu_section,
    },
    ComponentDoc {
        name: "MenuTrigger",
        slug: "menu-trigger",
        group: "Collections",
        page: collections::menu_trigger,
    },
    ComponentDoc {
        name: "Dropdown",
        slug: "dropdown",
        group: "Collections",
        page: collections_extra::dropdown,
    },
    ComponentDoc {
        name: "Select",
        slug: "select",
        group: "Collections",
        page: collections::select,
    },
    ComponentDoc {
        name: "ComboBox",
        slug: "combo-box",
        group: "Collections",
        page: collections::combo_box,
    },
    ComponentDoc {
        name: "Autocomplete",
        slug: "autocomplete",
        group: "Collections",
        page: collections::autocomplete,
    },
    ComponentDoc {
        name: "Command",
        slug: "command",
        group: "Collections",
        page: collections_command::command,
    },
    ComponentDoc {
        name: "DropdownMenu",
        slug: "dropdown-menu",
        group: "Collections",
        page: collections::dropdown_menu,
    },
    ComponentDoc {
        name: "Pagination",
        slug: "pagination",
        group: "Collections",
        page: collections::pagination,
    },
    ComponentDoc {
        name: "Tag",
        slug: "tag",
        group: "Collections",
        page: collections_groups::tag,
    },
    ComponentDoc {
        name: "TagGroup",
        slug: "tag-group",
        group: "Collections",
        page: collections::tag_group,
    },
    ComponentDoc {
        name: "StepList",
        slug: "step-list",
        group: "Collections",
        page: collections_extra::step_list,
    },
    ComponentDoc {
        name: "Table",
        slug: "table",
        group: "Collections",
        page: collections_extra::table,
    },
    ComponentDoc {
        name: "Tree",
        slug: "tree",
        group: "Collections",
        page: collections_extra::tree,
    },
    ComponentDoc {
        name: "Overlay",
        slug: "overlay",
        group: "Overlays",
        page: overlays::overlay,
    },
    ComponentDoc {
        name: "Underlay",
        slug: "underlay",
        group: "Overlays",
        page: overlays_extra::underlay,
    },
    ComponentDoc {
        name: "Popover",
        slug: "popover",
        group: "Overlays",
        page: overlays::popover,
    },
    ComponentDoc {
        name: "Modal",
        slug: "modal",
        group: "Overlays",
        page: overlays::modal,
    },
    ComponentDoc {
        name: "Dialog",
        slug: "dialog",
        group: "Overlays",
        page: overlays::dialog,
    },
    ComponentDoc {
        name: "AlertDialog",
        slug: "alert-dialog",
        group: "Overlays",
        page: overlays::alert_dialog,
    },
    ComponentDoc {
        name: "Sheet",
        slug: "sheet",
        group: "Overlays",
        page: overlays::sheet,
    },
    ComponentDoc {
        name: "BottomSheet",
        slug: "bottom-sheet",
        group: "Overlays",
        page: overlays_extra::bottom_sheet,
    },
    ComponentDoc {
        name: "Tray",
        slug: "tray",
        group: "Overlays",
        page: overlays_extra::tray,
    },
    ComponentDoc {
        name: "Drawer",
        slug: "drawer",
        group: "Overlays",
        page: overlays::drawer,
    },
    ComponentDoc {
        name: "Tooltip",
        slug: "tooltip",
        group: "Overlays",
        page: overlays::tooltip,
    },
    ComponentDoc {
        name: "HoverCard",
        slug: "hover-card",
        group: "Overlays",
        page: overlays::hover_card,
    },
    ComponentDoc {
        name: "ContextualHelp",
        slug: "contextual-help",
        group: "Overlays",
        page: overlays::contextual_help,
    },
    ComponentDoc {
        name: "Toast",
        slug: "toast",
        group: "Overlays",
        page: overlays::toast,
    },
    ComponentDoc {
        name: "ToastViewport",
        slug: "toast-viewport",
        group: "Overlays",
        page: overlays::toast_viewport,
    },
];
