mod actions;
mod actions_extra;
mod collections;
mod collections_extra;
mod display;
mod display_extra;
mod files;
mod forms;
mod forms_extra;
mod layout;
mod overlays;

use super::ComponentDoc;

pub(super) const CATALOG: &[ComponentDoc] = &[
    ComponentDoc {
        name: "Button",
        slug: "button",
        group: "Actions",
        page: actions::button,
    },
    ComponentDoc {
        name: "ActionBar",
        slug: "action-bar",
        group: "Actions",
        page: actions_extra::action_bar,
    },
    ComponentDoc {
        name: "ActionButton",
        slug: "action-button",
        group: "Actions",
        page: actions::action_button,
    },
    ComponentDoc {
        name: "ActionButtonGroup",
        slug: "action-button-group",
        group: "Actions",
        page: actions::action_button_group,
    },
    ComponentDoc {
        name: "ActionMenu",
        slug: "action-menu",
        group: "Actions",
        page: actions::action_menu,
    },
    ComponentDoc {
        name: "ButtonCopy",
        slug: "button-copy",
        group: "Actions",
        page: actions::button_copy,
    },
    ComponentDoc {
        name: "ButtonGroup",
        slug: "button-group",
        group: "Actions",
        page: actions::button_group,
    },
    ComponentDoc {
        name: "FlipButton",
        slug: "flip-button",
        group: "Actions",
        page: actions::flip_button,
    },
    ComponentDoc {
        name: "IconButton",
        slug: "icon-button",
        group: "Actions",
        page: actions::icon_button,
    },
    ComponentDoc {
        name: "LinkButton",
        slug: "link-button",
        group: "Actions",
        page: actions::link_button,
    },
    ComponentDoc {
        name: "SearchInputButton",
        slug: "search-input-button",
        group: "Actions",
        page: actions::search_input_button,
    },
    ComponentDoc {
        name: "ShareButton",
        slug: "share-button",
        group: "Actions",
        page: actions::share_button,
    },
    ComponentDoc {
        name: "ThemeToggleButton",
        slug: "theme-toggle-button",
        group: "Actions",
        page: actions::theme_toggle_button,
    },
    ComponentDoc {
        name: "ToggleButton",
        slug: "toggle-button",
        group: "Actions",
        page: actions::toggle_button,
    },
    ComponentDoc {
        name: "ToggleButtonGroup",
        slug: "toggle-button-group",
        group: "Actions",
        page: actions::toggle_button_group,
    },
    ComponentDoc {
        name: "Form",
        slug: "form",
        group: "Forms",
        page: forms::form,
    },
    ComponentDoc {
        name: "Input",
        slug: "input",
        group: "Forms",
        page: forms::input,
    },
    ComponentDoc {
        name: "Label",
        slug: "label",
        group: "Forms",
        page: forms_extra::label,
    },
    ComponentDoc {
        name: "InputGroup",
        slug: "input-group",
        group: "Forms",
        page: forms::input_group,
    },
    ComponentDoc {
        name: "TextField",
        slug: "text-field",
        group: "Forms",
        page: forms::text_field,
    },
    ComponentDoc {
        name: "TextArea",
        slug: "text-area",
        group: "Forms",
        page: forms::text_area,
    },
    ComponentDoc {
        name: "SearchField",
        slug: "search-field",
        group: "Forms",
        page: forms::search_field,
    },
    ComponentDoc {
        name: "NumberField",
        slug: "number-field",
        group: "Forms",
        page: forms::number_field,
    },
    ComponentDoc {
        name: "InputOtp",
        slug: "input-otp",
        group: "Forms",
        page: forms::input_otp,
    },
    ComponentDoc {
        name: "Checkbox",
        slug: "checkbox",
        group: "Forms",
        page: forms::checkbox,
    },
    ComponentDoc {
        name: "CheckboxGroup",
        slug: "checkbox-group",
        group: "Forms",
        page: forms::checkbox_group,
    },
    ComponentDoc {
        name: "Switch",
        slug: "switch",
        group: "Forms",
        page: forms::switch,
    },
    ComponentDoc {
        name: "RadioGroup",
        slug: "radio-group",
        group: "Forms",
        page: forms::radio_group,
    },
    ComponentDoc {
        name: "Radio",
        slug: "radio",
        group: "Forms",
        page: forms::radio,
    },
    ComponentDoc {
        name: "SegmentedControl",
        slug: "segmented-control",
        group: "Forms",
        page: forms::segmented_control,
    },
    ComponentDoc {
        name: "Slider",
        slug: "slider",
        group: "Forms",
        page: forms_extra::slider,
    },
    ComponentDoc {
        name: "Calendar",
        slug: "calendar",
        group: "Forms",
        page: forms_extra::calendar,
    },
    ComponentDoc {
        name: "DatePicker",
        slug: "date-picker",
        group: "Forms",
        page: forms_extra::date_picker,
    },
    ComponentDoc {
        name: "TimeField",
        slug: "time-field",
        group: "Forms",
        page: forms_extra::time_field,
    },
    ComponentDoc {
        name: "Card",
        slug: "card",
        group: "Layout",
        page: layout::card,
    },
    ComponentDoc {
        name: "Divider",
        slug: "divider",
        group: "Layout",
        page: layout::divider,
    },
    ComponentDoc {
        name: "Separator",
        slug: "separator",
        group: "Layout",
        page: layout::separator,
    },
    ComponentDoc {
        name: "Spacer",
        slug: "spacer",
        group: "Layout",
        page: layout::spacer,
    },
    ComponentDoc {
        name: "Well",
        slug: "well",
        group: "Layout",
        page: layout::well,
    },
    ComponentDoc {
        name: "ScrollShadow",
        slug: "scroll-shadow",
        group: "Layout",
        page: layout::scroll_shadow,
    },
    ComponentDoc {
        name: "AutoHeight",
        slug: "auto-height",
        group: "Layout",
        page: layout::auto_height,
    },
    ComponentDoc {
        name: "UiRoot",
        slug: "ui-root",
        group: "Layout",
        page: layout::ui_root,
    },
    ComponentDoc {
        name: "Alert",
        slug: "alert",
        group: "Display",
        page: display::alert,
    },
    ComponentDoc {
        name: "InlineAlert",
        slug: "inline-alert",
        group: "Display",
        page: display::inline_alert,
    },
    ComponentDoc {
        name: "Badge",
        slug: "badge",
        group: "Display",
        page: display::badge,
    },
    ComponentDoc {
        name: "StatusLight",
        slug: "status-light",
        group: "Display",
        page: display::status_light,
    },
    ComponentDoc {
        name: "Chip",
        slug: "chip",
        group: "Display",
        page: display::chip,
    },
    ComponentDoc {
        name: "Skeleton",
        slug: "skeleton",
        group: "Display",
        page: display::skeleton,
    },
    ComponentDoc {
        name: "CircularProgress",
        slug: "circular-progress",
        group: "Display",
        page: display::circular_progress,
    },
    ComponentDoc {
        name: "Spinner",
        slug: "spinner",
        group: "Display",
        page: display::spinner,
    },
    ComponentDoc {
        name: "Progress",
        slug: "progress",
        group: "Display",
        page: display::progress,
    },
    ComponentDoc {
        name: "ProgressBar",
        slug: "progress-bar",
        group: "Display",
        page: display::progress_bar,
    },
    ComponentDoc {
        name: "ProgressCircle",
        slug: "progress-circle",
        group: "Display",
        page: display::progress_circle,
    },
    ComponentDoc {
        name: "Meter",
        slug: "meter",
        group: "Display",
        page: display::meter,
    },
    ComponentDoc {
        name: "Code",
        slug: "code",
        group: "Display",
        page: display::code,
    },
    ComponentDoc {
        name: "CodeBlock",
        slug: "code-block",
        group: "Display",
        page: display::code_block,
    },
    ComponentDoc {
        name: "Kbd",
        slug: "kbd",
        group: "Display",
        page: display::kbd,
    },
    ComponentDoc {
        name: "Snippet",
        slug: "snippet",
        group: "Display",
        page: display::snippet,
    },
    ComponentDoc {
        name: "Link",
        slug: "link",
        group: "Display",
        page: display::link,
    },
    ComponentDoc {
        name: "LabeledValue",
        slug: "labeled-value",
        group: "Display",
        page: display_extra::labeled_value,
    },
    ComponentDoc {
        name: "Avatar",
        slug: "avatar",
        group: "Display",
        page: display::avatar,
    },
    ComponentDoc {
        name: "AvatarGroup",
        slug: "avatar-group",
        group: "Display",
        page: display::avatar_group,
    },
    ComponentDoc {
        name: "Image",
        slug: "image",
        group: "Display",
        page: display::image,
    },
    ComponentDoc {
        name: "IllustratedMessage",
        slug: "illustrated-message",
        group: "Display",
        page: display::illustrated_message,
    },
    ComponentDoc {
        name: "MotionRipple",
        slug: "motion-ripple",
        group: "Display",
        page: display::motion_ripple,
    },
    ComponentDoc {
        name: "StaticNumber",
        slug: "static-number",
        group: "Display",
        page: display::static_number,
    },
    ComponentDoc {
        name: "SlidingNumber",
        slug: "sliding-number",
        group: "Display",
        page: display::sliding_number,
    },
    ComponentDoc {
        name: "FileTrigger",
        slug: "file-trigger",
        group: "Files",
        page: files::file_trigger,
    },
    ComponentDoc {
        name: "DropZone",
        slug: "drop-zone",
        group: "Files",
        page: files::drop_zone,
    },
    ComponentDoc {
        name: "Breadcrumbs",
        slug: "breadcrumbs",
        group: "Collections",
        page: collections::breadcrumbs,
    },
    ComponentDoc {
        name: "Accordion",
        slug: "accordion",
        group: "Collections",
        page: collections::accordion,
    },
    ComponentDoc {
        name: "Disclosure",
        slug: "disclosure",
        group: "Collections",
        page: collections::disclosure,
    },
    ComponentDoc {
        name: "Tabs",
        slug: "tabs",
        group: "Collections",
        page: collections::tabs,
    },
    ComponentDoc {
        name: "ListBox",
        slug: "listbox",
        group: "Collections",
        page: collections::list_box,
    },
    ComponentDoc {
        name: "Menu",
        slug: "menu",
        group: "Collections",
        page: collections::menu,
    },
    ComponentDoc {
        name: "MenuTrigger",
        slug: "menu-trigger",
        group: "Collections",
        page: collections::menu_trigger,
    },
    ComponentDoc {
        name: "Select",
        slug: "select",
        group: "Collections",
        page: collections::select,
    },
    ComponentDoc {
        name: "ComboBox",
        slug: "combo-box",
        group: "Collections",
        page: collections::combo_box,
    },
    ComponentDoc {
        name: "Autocomplete",
        slug: "autocomplete",
        group: "Collections",
        page: collections::autocomplete,
    },
    ComponentDoc {
        name: "DropdownMenu",
        slug: "dropdown-menu",
        group: "Collections",
        page: collections::dropdown_menu,
    },
    ComponentDoc {
        name: "Pagination",
        slug: "pagination",
        group: "Collections",
        page: collections::pagination,
    },
    ComponentDoc {
        name: "TagGroup",
        slug: "tag-group",
        group: "Collections",
        page: collections::tag_group,
    },
    ComponentDoc {
        name: "Table",
        slug: "table",
        group: "Collections",
        page: collections_extra::table,
    },
    ComponentDoc {
        name: "Tree",
        slug: "tree",
        group: "Collections",
        page: collections_extra::tree,
    },
    ComponentDoc {
        name: "Overlay",
        slug: "overlay",
        group: "Overlays",
        page: overlays::overlay,
    },
    ComponentDoc {
        name: "Popover",
        slug: "popover",
        group: "Overlays",
        page: overlays::popover,
    },
    ComponentDoc {
        name: "Modal",
        slug: "modal",
        group: "Overlays",
        page: overlays::modal,
    },
    ComponentDoc {
        name: "Dialog",
        slug: "dialog",
        group: "Overlays",
        page: overlays::dialog,
    },
    ComponentDoc {
        name: "AlertDialog",
        slug: "alert-dialog",
        group: "Overlays",
        page: overlays::alert_dialog,
    },
    ComponentDoc {
        name: "Sheet",
        slug: "sheet",
        group: "Overlays",
        page: overlays::sheet,
    },
    ComponentDoc {
        name: "Drawer",
        slug: "drawer",
        group: "Overlays",
        page: overlays::drawer,
    },
    ComponentDoc {
        name: "Tooltip",
        slug: "tooltip",
        group: "Overlays",
        page: overlays::tooltip,
    },
    ComponentDoc {
        name: "HoverCard",
        slug: "hover-card",
        group: "Overlays",
        page: overlays::hover_card,
    },
    ComponentDoc {
        name: "ContextualHelp",
        slug: "contextual-help",
        group: "Overlays",
        page: overlays::contextual_help,
    },
    ComponentDoc {
        name: "ToastViewport",
        slug: "toast-viewport",
        group: "Overlays",
        page: overlays::toast_viewport,
    },
];
